---
- hosts: all
  vars:
    install_path: /opt
    java:
      set_default: True
      type: jdk
  roles:
    - wait-cloud-init
    #- wait-package-manager
    #- compatibility
    #- system
    #- packages
    #- java
