---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    install_path: /opt
    java:
      set_default: True
      type: jdk
  roles:
    - wait-cloud-init
    - wait-package-manager
    - compatibility
    - system
    - packages
    - java
