name: AWS arm java latest
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup Ansible and JMESPath
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            ansible==4.8.0
            jmespath

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: '1.7.8'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_SELLER }}
          aws-region: eu-west-3

      - name: Build image from template
        run: ./build-aws-arm-zulu.sh --java-major 21 --copy-regions true --profile default --latest true
