name: AWS x86 java latest
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install `python`
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install `ansible bundle`
        run: pip install ansible jmespath

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Install `packer plugins - Amazon`
        run: packer plugins install github.com/hashicorp/amazon

      - name: Install `packer plugins - Ansible`
        run: packer plugins install github.com/hashicorp/ansible

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_SELLER }}
          aws-region: eu-west-3

      - name: Build image from template
        run: ./build-aws-x86-zulu.sh --java-major 24 --copy-regions true --profile default --latest true
