name: AWS x86 java 11
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install `python`
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Install `ansible bundle`
        run: pip install ansible jmespath

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Init `packer`
        id: init
        run: cd packer; packer init aws-x86-zulu.pkr.hcl

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_SELLER }}
          aws-region: eu-west-3

      - name: Build image from template
        run: ./build-aws-x86-zulu.sh --java-major 11 --copy-regions true --profile default --latest false
