name: Azure x86 java 21
on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Image version (x.x.x)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Setup Ansible and JMESPath
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            ansible==4.8.0
            jmespath

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: '1.10.3'

      - name: Init Packer
        run: packer plugins install github.com/hashicorp/azure && packer plugins install github.com/hashicorp/ansible

      - name: Build image from template
        run: ./build-azure-x86-zulu.sh  --java-major 21 --client-id "${{ secrets.AZURE_CLIENT_ID }}" --client-secret "${{ secrets.AZURE_CLIENT_SECRET }}" --subscription-id "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --tenant-id "${{ secrets.AZURE_TENANT_ID }}" --image-version "${{ github.event.inputs.image_version }}"
