name: Azure x86 java 21
on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Image version (x.x.x)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install `python`
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install `ansible bundle`
        run: pip install ansible jmespath

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Install `packer plugins - Amazon`
        run: packer plugins install github.com/hashicorp/azure

      - name: Install `packer plugins - Ansible`
        run: packer plugins install github.com/hashicorp/ansible

      - name: Build image from template
        run: ./build-azure-x86-zulu.sh  --java-major 21 --client-id "${{ secrets.AZURE_CLIENT_ID }}" --client-secret "${{ secrets.AZURE_CLIENT_SECRET }}" --subscription-id "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --tenant-id "${{ secrets.AZURE_TENANT_ID }}" --image-version "${{ github.event.inputs.image_version }}"
