name: GCP x86 java 21
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Setup Ansible and JMESPath
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            ansible==4.8.0
            jmespath

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: '1.7.8'

      - name: Configure GCP Credentials
        run: |
          echo $ENV_FILE > creds.json;
        shell: bash
        env: 
          ENV_FILE: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} 

      - name: Build image from template
        run: export GOOGLE_APPLICATION_CREDENTIALS="./creds.json";  ./build-gcp-x86-zulu.sh  --java-major 21 --project-id "${{ secrets.GOOGLE_PROJECT_ID }}" --latest false
          
