name: GCP x86 graalvm 22
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
            packer-version: '1.7.8'


      - name: Build image from template
        run: cd packer; packer init gcp-x86-graal.pkr.hcl


      - name: Configure GCP Credentials
        run: |
          echo $ENV_FILE > creds.json;
        shell: bash
        env: 
          ENV_FILE: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} 

      - name: Build image from template
        run: export GOOGLE_APPLICATION_CREDENTIALS="./creds.json";  ./build-gcp-x86-graal.sh  --java-major 22 --graalvm-version 22.0.2 --project-id "${{ secrets.GOOGLE_PROJECT_ID }}" --latest false
          
